---
abstract: "SHARYANTO's default Pod::Weaver config"
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-PluginBundle-Author-SHARYANTO
requires:
  Pod::Weaver: 4.000
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Plugin::EnsureUniqueSections: 0
  Pod::Weaver::Plugin::Perinci: 0
  Pod::Weaver::Section::Bugs::DefaultRT: 0.03
  Pod::Weaver::Section::Homepage::DefaultCPAN: 0
  Pod::Weaver::Section::Source::DefaultGitHub: 0.04
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Weaver-PluginBundle-Author-SHARYANTO
  homepage: https://metacpan.org/release/Pod-Weaver-PluginBundle-Author-SHARYANTO
  repository: git://github.com/sharyanto/perl-Pod-Weaver-PluginBundle-Author-SHARYANTO.git
version: 0.09
